apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  config.js: |
    window.REACT_APP_BACKEND_URL={{.Values.backend | squote }}
---

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        volumeMounts:
          - name: {{.Values.name}}-config-vol
            mountPath: {{.Values.mountPath}}
            readOnly: true
            subPath: {{.Values.subPath}}
      volumes:
        - name: {{.Values.name}}-config-vol
          configMap:
            defaultMode: 420
            name: {{.Values.name}}